#!/bin/bash

while read a b; do
  let -i i="36#$a - 9" -i j="36#$b - 32"
  let -i n='j + ((4 + j - i) * 3) % 9'
  echo "$n"
done | {
  typeset -i s=0
  while read n; do : $((s += n)); done
  echo $s
}
