#!/bin/sh

awk '
  # rock
  $1 == "A" && $2 == "X" { print 3 + 0; next; }
  $1 == "A" && $2 == "Y" { print 1 + 3; next; }
  $1 == "A" && $2 == "Z" { print 2 + 6; next; }
  # paper
  $1 == "B" && $2 == "X" { print 1 + 0; next; }
  $1 == "B" && $2 == "Y" { print 2 + 3; next; }
  $1 == "B" && $2 == "Z" { print 3 + 6; next; }
  # scissors
  $1 == "C" && $2 == "X" { print 2 + 0; next; }
  $1 == "C" && $2 == "Y" { print 3 + 3; next; }
  $1 == "C" && $2 == "Z" { print 1 + 6; next; }
  { exit 1; }' | awk '
  {sum+=$0}
  END {print sum}'
