#!/bin/bash

typeset -ai p=(2 3 5 7 9 11)
while read a b; do
  let -i i=p[$((36#$a - 10))] -i j=p[$((36#$b - 30))]
  typeset s='987b136njf5@24'
  echo "${s:(i * j)%16-1:1}"
done \
  | { typeset -i s=0; while read n; do : $((s += n)); done; echo $s; }

